#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]; then echo "Использование: $0 <каталог> <расширение>"; exit 1; fi
dir="$1"
ext="$2"
archive="archive_$(date +%s).tar"
find "$dir" -type f -name "*$ext" | tar -cvf "$archive" -T -
echo "Архив $archive создан."
