#!/bin/bash
if [ -z "$1" ]; then echo "Использование: $0 <файл>"; exit 1; fi
filename="$1"
first_line=$(head -n 1 "$filename")
case "$filename" in
  *.c|*.js)
    if echo "$first_line" | grep -q "^//"; then echo "В файле $filename есть комментарий в первой строке."; else echo "В файле $filename нет комментария в первой строке."; fi
    ;;
  *.py)
    if echo "$first_line" | grep -q "^#"; then echo "В файле $filename есть комментарий в первой строке."; else echo "В файле $filename нет комментария в первой строке."; fi
    ;;
  *)
    echo "Неизвестный тип файла: $filename"
    ;;
esac
