#!/bin/bash
if [ -z "$1" ]; then echo "Использование: $0 <директория>"; exit 1; fi
find "$1" -type f -exec md5sum {} + | sort | awk '{count[$1]++; files[$1]=files[$1]"\n"$0} END {for (h in count) if (count[h]>1) print files[h]}'
